name: 'Makefile Build Target Finder'
description: 'Find build targets in Makefile with the specified dependencies'
author: 'meihei3'

inputs:
  makefile:
    description: 'The Makefile to find build targets from'
    default: 'Makefile'
    required: false
  dependencies:
    description: 'Files to find with dependencies (separated by spaces)'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.makefile }}
    - ${{ inputs.dependencies }}
