name: sandbox

on:
  push:
    branches:
      - main

jobs:
  runner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: this
        uses: ./
        with:
          dependencies: 'test1.txt test2.txt'
